// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var c, chart_id, future, present, q, t, wrapper, _i, _j, _len, _len1, _ref, _ref1;
    _ref = $("#dashboard_popup .chart");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      c = _ref[_i];
      chart_id = $(c).data('chart_id');
      wrapper = $(c).data('wrapper') || '#charts';
      charts.load(chart_id, null, {
        header: false,
        wrapper: wrapper,
        prunable: true
      });
    }
    _ref1 = window.targets.models;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      t = _ref1[_j];
      t.update_view();
    }
    q = gqueries.find_or_create_by_key('dashboard_bio_footprint');
    present = q.safe_present_value();
    future = q.safe_future_value();
    $("div.present .overlay").css('width', "" + (70 * present) + "px");
    return $("div.future  .overlay").css('width', "" + (70 * future) + "px");
  });

}).call(this);
