# ensures for now that blueprint_converter_id == excel_id, so we don't have to add a column to converters table (yet)
class AddBlueprintConverters < ActiveRecord::Migration
  def self.up
BlueprintConverter.create!(:excel_id => 1, :key => 'hot_water_demand', :name => 'hot water demand HH', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 2, :key => 'cooling_demand', :name => 'cooling demand HH', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 3, :key => 'oil_demand', :name => 'oil demand HH non-energetic', :use_id => 2, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 4, :key => 'heating_demand', :name => 'heating demand HH', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 5, :key => 'electricity_excl_heating_demand', :name => 'electricity demand HH (excl heating)', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 6, :key => 'led_lighting', :name => 'LED lighting', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 7, :key => 'efficient_lighting', :name => 'efficient lighting', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 8, :key => 'traditional_lighting', :name => 'traditional lighting', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 9, :key => 'electricity_demand_lighting', :name => 'electricity demand lighting', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 10, :key => 'other_appliances', :name => 'other appliances (incl cooking)', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 11, :key => 'solar_panel_for_hot_water', :name => 'solar panel for hot water', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 12, :key => 'heatpump_boiler', :name => 'heatpump boiler', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 13, :key => 'electric_boiler', :name => 'electric boiler', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 14, :key => 'heat_pump_with_chs', :name => 'heatpump with TS', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 15, :key => 'airco', :name => 'airco', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 16, :key => 'electric_heater', :name => 'electric heater', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 17, :key => 'solar_panel_for_heating', :name => 'solar panel for heating', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 18, :key => 'micro_chp', :name => 'micro CHP', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 19, :key => 'central_heating', :name => 'central heating (CV)', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 20, :key => 'solar_pv_central_production', :name => 'solar PV central production', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 21, :key => 'lv_electricity_network', :name => 'LV electricity network', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 22, :key => 'city_heating_network', :name => 'city heating network', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 23, :key => 'gas_conv', :name => 'Gas conventional', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 24, :key => 'electricity_demand', :name => 'electricity demand industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 25, :key => 'heating_demand', :name => 'heating demand industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 26, :key => 'mv_distribution_network', :name => 'MV distribution network', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 27, :key => 'small_chp', :name => 'small CHP industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 28, :key => 'large_chp', :name => 'large CHP industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 29, :key => 'biomass_chp', :name => 'biomass CHP industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 30, :key => 'biomass_demand_appliences_', :name => 'biomass demand appliances', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 31, :key => 'trains_diesel_demand', :name => 'trains diesel demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 32, :key => 'truck_kms_demand', :name => 'truck kms demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 33, :key => 'cars_kms_demand', :name => 'car kms demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 34, :key => 'electric_trucks', :name => 'electric trucks', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 35, :key => 'diesel_trucks', :name => 'diesel trucks', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 36, :key => 'gasoline_trucks', :name => 'gasoline trucks', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 37, :key => 'electric_cars', :name => 'electric cars', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 38, :key => 'diesel_cars', :name => 'diesel cars', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 39, :key => 'gasoline_cars', :name => 'gasoline cars', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 40, :key => 'lpg_cars', :name => 'LPG cars', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 41, :key => 'compressed_gas_trucks', :name => 'compressed gas trucks', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 42, :key => 'compressed_gas_cars', :name => 'compressed gas cars', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 43, :key => 'electricity_distribution_transport', :name => 'electricity distribution transport', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 44, :key => 'oil_demand', :name => 'oil demand transport non-energetic', :use_id => 2, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 45, :key => 'oil_demand_households_appliances', :name => 'oil demand households appliances', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 46, :key => 'ships_oil_demand', :name => 'ships oil demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 47, :key => 'ships_diesel_demand', :name => 'ships diesel demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 48, :key => 'trains_electricity_demand', :name => 'trains electricity demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 49, :key => 'built_environment_cooling_demand', :name => 'cooling demand built environment', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 50, :key => 'built_environment_heating_demand', :name => 'heating demand built environment', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 51, :key => 'built_environment_electricity_demand', :name => 'electricity demand built environment', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 52, :key => 'heatpump', :name => 'heatpump', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 53, :key => 'local_heat_network', :name => 'local heat network industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 54, :key => 'appliances_gas_demand', :name => 'appliances gas demand', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 55, :key => 'cooling_demand', :name => 'cooling demand agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 56, :key => 'heating_demand', :name => 'heating demand agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 57, :key => 'gas_demand', :name => 'gas demand agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 58, :key => 'electricity_demand', :name => 'electricity demand agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 59, :key => 'cooling_demand', :name => 'cooling demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 60, :key => 'coal_demand_households_appliances', :name => 'coal demand households appliances', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 61, :key => 'trains_coal_demand', :name => 'trains coal demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 62, :key => 'electricity_demand', :name => 'electricity demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 63, :key => 'heat_network', :name => 'heat network', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 64, :key => 'waste_incinerator', :name => 'Waste incinerator', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 65, :key => 'hv_electricity_network', :name => 'HV electricity network', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 66, :key => 'coal_pwd', :name => 'Coal pwd', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 67, :key => 'coal_pwd_ccs', :name => 'Coal pwd CCS', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 68, :key => 'coal_conv', :name => 'Coal Conv.', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 69, :key => 'coal_lignite', :name => 'Coal Lignite', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 70, :key => 'coal_oxyfuel_ccs', :name => 'Coal Oxyfuel CCS', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 71, :key => 'coal_igcc', :name => 'Coal IGCC', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 72, :key => 'coal_igcc_ccs', :name => 'Coal IGCC CCS', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 73, :key => 'oil_plant', :name => 'Oil plant', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 74, :key => 'gas_ccgt', :name => 'Gas CCGT', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 75, :key => 'coal_chp', :name => 'Coal CHP', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 76, :key => 'heatpump_boiler_using_city_heat', :name => 'Hot water from heat network', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 77, :key => 'bio_oil_chp', :name => 'Bio-oil CHP industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 78, :key => 'interconnection', :name => 'interconnection', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 79, :key => 'nuclear_iii', :name => 'Nuclear III', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 80, :key => 'wind_inland', :name => 'Wind inland', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 81, :key => 'wind_coastal', :name => 'Wind coastal', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 82, :key => 'wind_offshore', :name => 'Wind offshore', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 83, :key => 'co_firing_coal', :name => 'Co-firing coal', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 84, :key => 'co_firing_gas', :name => 'Co-firing gas', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 85, :key => 'solar_csp', :name => 'Solar CSP', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 86, :key => 'geothermal_heat', :name => 'Geothermal heat', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 87, :key => 'hydro_river', :name => 'Hydro river', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 88, :key => 'hydro_mount', :name => 'Hydro Mount.', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 89, :key => 'blue_energy', :name => 'Blue energy', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 90, :key => 'geothermal_electricity', :name => 'Geothermal electricity', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 91, :key => 'national_gas_network', :name => 'national gas network', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 92, :key => 'gas_treatment', :name => 'gas treatment', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 93, :key => 'diesel_distribution', :name => 'diesel distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 94, :key => 'gasoline_distribution', :name => 'gasoline distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 95, :key => 'kerosine_distribution', :name => 'kerosine distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 96, :key => 'bio_diesel_distribution', :name => 'bio-diesel distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 97, :key => 'bio_ethanol_distribution', :name => 'bio-ethanol distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 98, :key => 'biofuel_distribution', :name => 'biofuel distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 99, :key => 'lpg_distribution', :name => 'LPG distribution', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 100, :key => 'bio_oil_production', :name => 'bio-oil production', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 101, :key => 'biomass_residuals', :name => 'biomass residuals', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 102, :key => 'gas_extraction', :name => 'gas extraction', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 103, :key => 'bio_oil_distribution', :name => 'bio-oil distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 104, :key => 'oil_extraction', :name => 'oil extraction', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 105, :key => 'lng_import', :name => 'LNG import', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 106, :key => 'coal_extraction', :name => 'coal extraction', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 107, :key => 'uranium_import', :name => 'uranium import', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 108, :key => 'compressed_gas_distribution', :name => 'compressed gas distribution', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 109, :key => 'oil_distribution', :name => 'oil distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 110, :key => 'environment', :name => 'environment', :use_id => 3, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 111, :key => 'biomass_distribution', :name => 'biomass distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 112, :key => 'greengas_distribution', :name => 'greengas distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 113, :key => 'coal_distribution', :name => 'coal distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 114, :key => 'coal_demand', :name => 'coal demand other energetic', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 115, :key => 'oil_demand', :name => 'oil demand other energetic', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 116, :key => 'oil_demand', :name => 'Oil demand industry energetic', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 117, :key => 'gas_demand', :name => 'Gas demand industry energetic', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 118, :key => 'greengas_demand', :name => 'Greengas demand industry non energy', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 119, :key => 'coal_demand', :name => 'Coal demand industry non energetic', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 120, :key => 'biomass_demand', :name => 'Biomass demand industry', :use_id => 3, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 121, :key => 'steam_hot_water_demand', :name => 'Steam/hot water demand industry', :use_id => 3, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 122, :key => 'biofuel_demand', :name => 'Biofuel demand industry', :use_id => 3, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 123, :key => 'gas_demand', :name => 'gas demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 124, :key => 'biofuel_demand', :name => 'biofuel demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 125, :key => 'trains_oil_demand', :name => 'trains oil demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 126, :key => 'lpg_production', :name => 'LPG production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 127, :key => 'diesel_production', :name => 'diesel production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 128, :key => 'gasoline_production', :name => 'gasoline production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 129, :key => 'kerosine_production', :name => 'kerosine production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 130, :key => 'bio_diesel_production', :name => 'bio-diesel production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 131, :key => 'bio_ethanol_production', :name => 'bio-ethanol production', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 132, :key => 'biofuel_production', :name => 'biofuel production', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 133, :key => 'greengas_production', :name => 'greengas production', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 134, :key => 'oil_treatment', :name => 'oil treatment', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 135, :key => 'coal_treatment', :name => 'coal treatment', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 136, :key => 'uranium_treatment', :name => 'uranium treatment', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 137, :key => 'uranium_distribution', :name => 'uranium distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 138, :key => 'oil_import_export', :name => 'oil import / export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 139, :key => 'gas_import_export', :name => 'gas import / export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 140, :key => 'biomass_import_export', :name => 'biomass import / export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 141, :key => 'planes_kerosine_demand', :name => 'planes kerosine demand', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 142, :key => 'diesel_import_export', :name => 'diesel import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 143, :key => 'gasoline_import_export', :name => 'gasoline import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 144, :key => 'kerosine_import_export', :name => 'kerosine import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 145, :key => 'bio_diesel_import_export', :name => 'bio-diesel import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 146, :key => 'bio_ethanol_import_export', :name => 'bio-ethanol import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 147, :key => 'biofuel_import_export', :name => 'biofuel import / export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 148, :key => 'lpg_import_export', :name => 'LPG import / export', :use_id => 3, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 149, :key => 'planes_oil_demand', :name => 'planes oil demand', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 150, :key => 'coal_demand', :name => 'coal demand other non energy', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 151, :key => 'oil_demand', :name => 'oil demand other non energy', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 152, :key => 'oil_demand', :name => 'Oil demand industry non energy', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 153, :key => 'gas_demand', :name => 'Gas demand industry non energy', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 154, :key => 'local_wind_turbines', :name => 'local wind turbines', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 155, :key => 'coal_demand_transport', :name => 'Coal demand transport', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 156, :key => 'biomass_demand', :name => 'Biomass demand industry non energy', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 157, :key => 'cv_hot_water', :name => 'CV hot water', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 158, :key => 'biofuel_demand', :name => 'Biofuel demand industry non energy', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 159, :key => 'gas_demand', :name => 'gas demand other non energy', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 160, :key => 'coal_demand', :name => 'Coal demand industry energetic', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 161, :key => 'electricity_demand', :name => 'Electricity demand non energetic industry', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 162, :key => 'electricity', :name => 'energetic use agriculture electricity', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 163, :key => 'gas', :name => 'energetic use agriculture gas', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 164, :key => 'oil', :name => 'energetic use agriculture oil', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 165, :key => 'steam_hot_water', :name => 'energetic use agriculture steam / hot water', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 166, :key => 'biofuel_demand', :name => 'biofuel demand other non energy', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 167, :key => 'biomass', :name => 'energetic use households biomass', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 168, :key => 'coal', :name => 'energetic use households coal', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 169, :key => 'electricity', :name => 'energetic use households electricity', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 170, :key => 'gas', :name => 'energetic use households gas', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 171, :key => 'greengas', :name => 'energetic use households greengas', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 172, :key => 'oil', :name => 'energetic use households oil', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 173, :key => 'steam_hot_water', :name => 'energetic use households steam / hot water', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 174, :key => 'biofuel', :name => 'energetic use industry biofuel', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 175, :key => 'biomass', :name => 'energetic use industry biomass', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 176, :key => 'coal', :name => 'energetic use industry coal', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 177, :key => 'electricity', :name => 'energetic use industry electricity', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 178, :key => 'gas', :name => 'energetic use industry gas', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 179, :key => 'greengas', :name => 'energetic use industry greengas', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 180, :key => 'oil', :name => 'energetic use industry oil', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 181, :key => 'steam_hot_water', :name => 'energetic use industry steam / hot water', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 182, :key => 'trains_oil_demand', :name => 'trains oil demand non energy', :use_id => 2, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 183, :key => 'biofuel', :name => 'energetic use other biofuel', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 184, :key => 'biomass', :name => 'energetic use other biomass', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 185, :key => 'coal', :name => 'energetic use other coal', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 186, :key => 'electricity', :name => 'energetic use other electricity', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 187, :key => 'gas', :name => 'energetic use other gas', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 188, :key => 'oil', :name => 'energetic use other oil', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 189, :key => 'steam_hot_water', :name => 'energetic use other steam / hot water', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 190)
BlueprintConverter.create!(:excel_id => 191, :key => 'biofuel', :name => 'energetic use transport biofuel', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 192, :key => 'coal', :name => 'energetic use transport coal', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 193, :key => 'electricity', :name => 'energetic use transport electricity', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 194, :key => 'diesel', :name => 'energetic use transport diesel', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 195, :key => 'kerosine', :name => 'energetic use transport kerosine', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 196, :key => 'oil', :name => 'energetic use transport oil', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 197, :key => 'gas', :name => 'non energetic use agriculture gas', :use_id => 2, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 198, :key => 'oil', :name => 'non energetic use households oil', :use_id => 2, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 199, :key => 'biofuel', :name => 'non energetic use industry biofuel', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 200, :key => 'biomass', :name => 'non energetic use industry biomass', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 201, :key => 'coal', :name => 'non energetic use industry coal', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 202, :key => 'electricity', :name => 'non energetic use industry electricity', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 203, :key => 'gas', :name => 'non energetic use industry gas', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 204, :key => 'greengas', :name => 'non energetic use industry greengas', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 205, :key => 'oil', :name => 'non energetic use industry oil', :use_id => 2, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 206, :key => 'heatpump_using_city_heat', :name => '', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 207, :key => 'biofuel', :name => 'non energetic use other biofuel', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 208, :key => 'coal', :name => 'non energetic use other coal', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 209, :key => 'gas', :name => 'non energetic use other gas', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 210, :key => 'oil', :name => 'non energetic use other oil', :use_id => 2, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 211, :key => 'oil', :name => 'non energetic use transport oil', :use_id => 2, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 212, :key => 'heater_on_biomass', :name => 'heater on biomass hh', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 213, :key => 'heater_on_coal', :name => 'heater on coal hh', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 214, :key => 'heater_on_greengas', :name => 'heater on greengas hh', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 215, :key => 'heater_on_oil', :name => 'heater on oil hh', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 216, :key => 'gas_demand', :name => 'energetic use transport gas', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 217, :key => 'effective_lighting_demand', :name => 'effective lighting demand HH', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 218, :key => 'oil_demand', :name => 'agriculture oil demand energetic', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 219, :key => 'steam_hot_water_demand', :name => 'agriculture steam / hot water demand', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 220, :key => 'biomass_demand', :name => 'biomass demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 221, :key => 'greengas_demand', :name => 'greengas demand industry energetic', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 222, :key => 'steam_hot_water_demand', :name => 'other steam / hot water demand', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 223, :key => 'grid_losses_electricity', :name => 'grid losses electricity', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 224, :key => 'grid_losses_oil', :name => 'grid losses oil', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 225, :key => 'grid_losses_gas', :name => 'grid losses gas', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 226, :key => 'grid_losses_heat_network', :name => 'grid losses heat network', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 227, :key => 'electricity_demand', :name => 'energy sector use electricity', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 228, :key => 'oil_demand', :name => 'energy sector use oil', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 229, :key => 'gas_demand', :name => 'energy sector use gas', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 230, :key => 'heat_demand', :name => 'energy sector use heat', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 231, :key => 'local_solar_pv_grid_connected', :name => 'local solar PV grid connected', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 232, :key => 'local_electricity_storage', :name => 'local electricity storage', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 233, :key => 'local_heat_storage', :name => 'local heat storage', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 234, :key => 'electricity_demand_cleaning', :name => 'electricity demand cleaning', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 235, :key => 'electricity_demand_audio_video', :name => 'electricity demand audio/video', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 236, :key => 'electricity_demand_fridge_freezer', :name => 'electricity demand fridge/freezer', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 237, :key => 'steam_hot_water_demand_appliances', :name => 'Steam/hot water energetic demand household appliances', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 238, :key => 'local_solar_pv_not_grid_connected', :name => 'local solar PV not grid connected', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 239, :key => 'gasheatpump', :name => 'gasheatpump', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 240, :key => 'uranium_extraction', :name => 'uranium extraction', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 241, :key => 'waste_collection', :name => 'waste collection', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 242, :key => 'greengas_import_export', :name => 'greengas import/export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 243, :key => 'coal_import_export', :name => 'coal import/export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 244, :key => 'biomass_growth', :name => 'biomass growth', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 245, :key => 'heat_network_unused', :name => 'heat network unused', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 246, :key => 'bio_oil_import_export', :name => 'bio-oil import/export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 247, :key => 'oil_storage', :name => 'oil storage', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 248, :key => 'gas_storage', :name => 'gas storage', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 249, :key => 'electricity_import_export', :name => 'electricity import / export', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 250, :key => 'earth', :name => 'earth', :use_id => 1, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 251, :key => 'water', :name => 'water', :use_id => 1, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 252, :key => 'CNG_distribution', :name => 'CNG distribution', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 253, :key => 'CNG_production', :name => 'CNG production', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 254, :key => 'greengas', :name => 'energetic use transport greengas', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 255, :key => 'compressed_gas_production', :name => 'compressed gas production', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 256, :key => 'algue_diesel_production', :name => 'algue diesel production', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 257, :key => 'sun', :name => 'sun', :use_id => 1, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 258, :key => 'air', :name => 'air', :use_id => 1, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 259, :key => 'heat_overflow_households', :name => 'heat overflow households', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 260, :key => 'hot_water_overflow_households', :name => 'hot water overflow households', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 261, :key => 'chp_other', :name => 'chp other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 262, :key => 'biomass_burner_agri', :name => 'biomass burner agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 263, :key => 'oil_burner_agri', :name => 'oil burner agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 264, :key => 'gas_burner_agri', :name => 'gas burner agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 265, :key => 'chp_agri', :name => 'chp agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 266, :key => 'heat_demand_other', :name => 'heat demand other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 267, :key => 'coal_burner_other', :name => 'coal burner other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 268, :key => 'oil_burner_other', :name => 'oil burner other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 269, :key => 'biomass_burner_other', :name => 'biomass burner other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 270, :key => 'gas_burner_other', :name => 'gas burner other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 271, :key => 'biomass_boiler', :name => 'biomass boiler', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 272, :key => 'lignite_extraction', :name => 'lignite extraction', :use_id => 1, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 273, :key => 'coal_burner_industry', :name => 'coal burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 274, :key => 'oil_burner_industry', :name => 'oil burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 275, :key => 'biomass_burner_industry', :name => 'biomass burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 276, :key => 'gas_burner_industry', :name => 'gas burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 277, :key => 'biofuel_burner_industry', :name => 'biofuel burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 278, :key => 'greengas_burner_industry', :name => 'greengas burner industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 279, :key => 'heat_pump_with_CHS_agri', :name => 'heatpump with TS agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 280, :key => 'geothermal_agri', :name => 'geothermal agri', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 281, :key => 'energetic_use_biomass_agriculture', :name => 'energetic use biomass agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 282, :key => 'waste_import_export', :name => 'waste import / export', :use_id => 3, :sector_id => 7)
BlueprintConverter.create!(:excel_id => 283, :key => 'lignite_distribution', :name => 'lignite distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 284, :key => 'waste_distribution', :name => 'waste distribution', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 285, :key => 'heating_demand_with_current_insulation', :name => 'heating demand with current insulation', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 286, :key => 'extra_insulation_savings', :name => 'extra insulation savings', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 287, :key => 'energy_sector_gas_mixer', :name => 'energy sector gas mixer', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 288, :key => 'greengas_for_electricity_production', :name => 'greengas for electricity production', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 289, :key => 'algue_diesel_distribution', :name => 'algue diesel distribution', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 290, :key => 'algue_diesel_import_export', :name => 'algue diesel import / export', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 291, :key => 'lpg_trucks', :name => 'LPG trucks', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 292, :key => 'greengas_use', :name => 'energy sector use greengas', :use_id => 1, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 293, :key => 'coal_boiler', :name => 'coal boiler', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 294, :key => 'oil_boiler', :name => 'oil boiler', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 295, :key => 'other_electric_transport', :name => 'Other electric transport', :use_id => 1, :sector_id => 3)
BlueprintConverter.create!(:excel_id => 296, :key => 'biofuel_burner_other', :name => 'biofuel burner other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 297, :key => 'savings_because_of_HR_glass', :name => 'savings because of HR glass', :use_id => 1, :sector_id => 1)
BlueprintConverter.create!(:excel_id => 298, :key => 'unused_CHPs_heat_industry', :name => 'unused CHPs heat industry', :use_id => 1, :sector_id => 2)
BlueprintConverter.create!(:excel_id => 299, :key => 'unused_CHPs_heat_other', :name => 'unused CHPs heat other', :use_id => 1, :sector_id => 6)
BlueprintConverter.create!(:excel_id => 300, :key => 'unused_CHPs_heat_agriculture', :name => 'unused CHPs heat agriculture', :use_id => 1, :sector_id => 4)
BlueprintConverter.create!(:excel_id => 301, :key => 'lv_mv_transformer', :name => 'LV-MV transformer', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 302, :key => 'mv_transport_network', :name => 'MV transport network', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 303, :key => 'mv_hv_transformer', :name => 'MV-HV transformer', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 304, :key => 'foreign_gas_power_plants', :name => 'foreign gas power plants', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 305, :key => 'foreign_nuclear_power_plants', :name => 'foreign nuclear power plants', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 306, :key => 'foreign_coal_power_plants', :name => 'foreign coal power plants', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 307, :key => 'foreign_sustainable_power_production', :name => 'foreign sustainable power production', :use_id => 3, :sector_id => 5)
BlueprintConverter.create!(:excel_id => 308, :key => 'backup_burner_heat_network', :name => 'backup burner heat network', :use_id => 3, :sector_id => 5)

  end

  def self.down
  end
end
