# ensures for now that blueprint_carrier_id == excel_id, so we don't have to add a column to carriers table (yet)
class AddBlueprintCarriers < ActiveRecord::Migration
  def self.up
    BlueprintCarrier.create!(:excel_id => 1, :name => 'loss', :key => 'loss', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 2, :name => 'hot water', :key => 'hot_water', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 3, :name => 'crude oil', :key => 'crude_oil', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 4, :name => 'steam / hot water', :key => 'steam_hot_water', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 5, :name => 'electricity', :key => 'electricity', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 6, :name => 'solar radiation', :key => 'solar_radiation', :infinite => true)
    BlueprintCarrier.create!(:excel_id => 7, :name => 'ambient heat', :key => 'ambient_heat', :infinite => true)
    BlueprintCarrier.create!(:excel_id => 8, :name => 'ambient cold', :key => 'ambient_cold', :infinite => true)
    BlueprintCarrier.create!(:excel_id => 9, :name => 'natural gas', :key => 'natural_gas', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 10, :name => 'useable heat', :key => 'useable_heat', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 11, :name => 'biomass', :key => 'biomass', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 12, :name => 'biofuel', :key => 'biofuel', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 13, :name => 'greengas', :key => 'greengas', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 14, :name => 'coal', :key => 'coal', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 15, :name => 'gasoline', :key => 'gasoline', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 16, :name => 'diesel', :key => 'diesel', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 17, :name => 'LPG', :key => 'lpg', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 18, :name => 'biodiesel', :key => 'biodiesel', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 19, :name => 'bio-ethanol', :key => 'bio_ethanol', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 20, :name => 'kerosine', :key => 'kerosine', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 21, :name => 'waste', :key => 'waste', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 22, :name => 'uranium', :key => 'uranium', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 23, :name => 'wind', :key => 'wind', :infinite => true)
    BlueprintCarrier.create!(:excel_id => 24, :name => 'bio-oil', :key => 'bio_oil', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 25, :name => 'water', :key => 'water', :infinite => true)
    BlueprintCarrier.create!(:excel_id => 26, :name => 'low caloric gas', :key => 'low_caloric_gas', :infinite => false)

    BlueprintCarrier.create!(:excel_id => 27, :name => 'high caloric gas', :key => 'high_caloric_gas', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 28, :name => 'LNG', :key => 'lng', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 29, :name => 'cooling', :key => 'cooling', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 30, :name => 'car kms', :key => 'car_kms', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 31, :name => 'truck kms', :key => 'truck_kms', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 32, :name => 'light', :key => 'light', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 33, :name => 'Algae diesel', :key => 'algae_diesel', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 34, :name => 'biogas', :key => 'biogas', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 35, :name => 'Lignite', :key => 'lignite', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 36, :name => 'CNG', :key => 'cng', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 37, :name => 'imported electricity', :key => 'imported_electricity', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 38, :name => 'Compressed gas', :key => 'compressed_gas', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 39, :name => 'overflow', :key => 'overflow', :infinite => false)
    BlueprintCarrier.create!(:excel_id => 40, :name => 'gasmix', :key => 'gasmix', :infinite => false)
  end

  def self.down
    BlueprintCarrier.all.each {|bc| bc.destroy!}
  end
end
