---
- label: electricity_stored_in_household_batteries
  color: "#dd33cc"
  order_by: 100
  group: 
  show_at_first:
  is_target_line: 
  target_line_position: 
  gquery: households_flexibility_p2p_electricity_storage_curve
  is_1990: 
  dependent_on: 
  output_element_key: flexibility_hourly_p2p_storage
  key: electricity_stored_in_household_batteries_flexibility_hourly_p2p_storage