---
- label: heat
  color: "#8B0000"
  order_by: 5
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_heat_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: heat_use_of_final_demand_in_industry_chemical_detailed
- label: coal_and_derivatives
  color: "#333333"
  order_by: 10
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_coal_and_derivatives_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: coal_and_derivatives_use_of_final_demand_in_industry_chemical_detailed
- label: coal_and_derivatives_non_energetic
  color: "#000000"
  order_by: 15
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_coal_and_derivatives_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: coal_and_derivatives_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: network_gas_energetic
  color: "#CCCCCC"
  order_by: 20
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: natural_gas_and_derivatives_use_of_final_demand_in_industry_chemical_detailed
- label: network_gas_non_energetic
  color: "#A9A9A9"
  order_by: 25
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_natural_gas_and_derivatives_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: natural_gas_and_derivatives_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: oil_energetic
  color: "#BA7D40"
  order_by: 30
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_oil_and_derivatives_excl_refinery_gas_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: oil_and_derivatives_use_of_final_demand_in_industry_chemical_detailed
- label: oil_and_derivatives_non_energetic
  color: "#854321"
  order_by: 35
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_oil_and_derivatives_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: oil_and_derivatives_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: solar
  color: "#FFD900"
  order_by: 40
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_solar_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: solar_use_of_final_demand_in_industry_chemical_detailed
- label: refinery_gas_energetic
  color: "#BC8F8F"
  order_by: 45
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_refinery_gas_in_chemical_industry_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: refinery_gas_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: ambient
  color: "#ADDE4C"
  order_by: 50
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_ambient_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: ambient_use_of_final_demand_in_industry_chemical_detailed
- label: electricity
  color: "#4169E1"
  order_by: 55
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_electricity_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: electricity_use_of_final_demand_in_industry_chemical_detailed
- label: biomass_products
  color: "#5D7929"
  order_by: 60
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_biomass_products_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: biomass_products_use_of_final_demand_in_industry_chemical_detailed
- label: geothermal
  color: "#FF8400"
  order_by: 65
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_geothermal_in_chemical_industry_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: geothermal_use_of_final_demand_in_industry_chemical_detailed
- label: biomass_products_non_energetic
  color: "#006400"
  order_by: 70
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_biomass_products_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: biomass_products_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: hydrogen
  color: "#87CEEB"
  order_by: 75
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_chemical_industry_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: hydrogen_use_of_final_demand_in_industry_chemical_detailed
- label: hydrogen_non_energetic
  color: "#BFEFFF"
  order_by: 80
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_hydrogen_in_chemical_industry_non_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: hydrogen_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: ammonia_non_energetic
  color: "#1ce6d6"
  order_by: 85
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_ammonia_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: ammonia_non_energetic_use_of_final_demand_in_industry_chemical_detailed
- label: methanol_non_energetic
  color: "#FF8C8C"
  order_by: 90
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: final_demand_of_methanol_in_chemical_industry_non_energetic
  is_1990:
  dependent_on:
  output_element_key: use_of_final_demand_in_industry_chemical_detailed
  key: methanol_non_energetic_use_of_final_demand_in_industry_chemical_detailed
