---
- key: costs_fuel_production_processes
  position: 10
  sidebar_item_key: costs_fuel_production
  output_element_key: costs_overview_detailed
- group_sub_header: share
  key: external_coupling_efficiency_fuel_production_processes
  position: 20
  sidebar_item_key: costs_fuel_production
  output_element_key: costs_overview_detailed
