---
- key: costs_bio_ethanol_production
  position: 10
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_bio_ethanol_to_jet
  position: 20
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_fischer_tropsch
  position: 30
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_hydrotreatment
  position: 40
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_methanol_synthesis
  position: 50
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_methanol_to_jet
  position: 60
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_pyrolysis_fractionation
  position: 70
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
- group_sub_header: share
  key: costs_pyrolysis_production
  position: 80
  sidebar_item_key: costs_fuel_production
  output_element_key: liquid_fuels
