---
- key: scenario_overview
  position: 5
  sidebar_item_key: introduction
  output_element_key: sankey_energy_overview
- key: electricity
  position: 10
  sidebar_item_key: introduction
  output_element_key: sankey_electrical_interconnection
- key: heat
  position: 15
  sidebar_item_key: introduction
  output_element_key: sankey_heat_networks
- key: carbon
  position: 20
  sidebar_item_key: introduction
  output_element_key: liquid_fuels
- key: hydrogen
  position: 25
  sidebar_item_key: introduction
  output_element_key: mekko_of_hydrogen_network
