---
- key: investment_costs_combustion_gas_plant
  interface_group: costs
  step_value: 1.0
  unit: "%"
  command_type: value
  related_node: energy_power_combined_cycle_network_gas
  position: 100
  slide_key: specs_electricity_gas_plants
- key: om_costs_combustion_gas_plant
  interface_group: costs
  step_value: 1.0
  unit: "%"
  position: 105
  slide_key: specs_electricity_gas_plants

- key: efficiency_energy_power_combined_cycle_network_gas
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_power_combined_cycle_network_gas
  position: 200
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_turbine_network_gas
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_power_turbine_network_gas
  position: 240
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_ultra_supercritical_network_gas
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_power_ultra_supercritical_network_gas
  position: 245
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_power_engine_network_gas
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_power_engine_network_gas
  position: 250
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_combined_cycle_network_gas_electricity
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_combined_cycle_network_gas
  position: 255
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_combined_cycle_network_gas_heat
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_combined_cycle_network_gas
  position: 260
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_local_engine_network_gas_electricity
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_engine_network_gas
  position: 265
  slide_key: specs_electricity_gas_plants
- key: efficiency_energy_chp_local_engine_network_gas_heat
  interface_group: efficiency_energy_plants
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_engine_network_gas
  position: 270
  slide_key: specs_electricity_gas_plants

- key: efficiency_industry_chp_combined_cycle_gas_power_fuelmix_electricity
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_combined_cycle_gas_power_fuelmix
  position: 335
  slide_key: specs_electricity_gas_plants
- key: efficiency_industry_chp_combined_cycle_gas_power_fuelmix_heat
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_combined_cycle_gas_power_fuelmix
  position: 340
  slide_key: specs_electricity_gas_plants
- key: efficiency_industry_chp_engine_gas_power_fuelmix_electricity
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_engine_gas_power_fuelmix
  position: 345
  slide_key: specs_electricity_gas_plants
- key: efficiency_industry_chp_engine_gas_power_fuelmix_heat
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_engine_gas_power_fuelmix
  position: 350
  slide_key: specs_electricity_gas_plants
- key: efficiency_industry_chp_turbine_gas_power_fuelmix_electricity
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_turbine_gas_power_fuelmix
  position: 355
  slide_key: specs_electricity_gas_plants
- key: efficiency_industry_chp_turbine_gas_power_fuelmix_heat
  interface_group: efficiency_industry_plants
  step_value: 1.0
  unit: "%"
  related_node: industry_chp_turbine_gas_power_fuelmix
  position: 360
  slide_key: specs_electricity_gas_plants

- key: efficiency_agriculture_chp_engine_dispatchable_network_gas_electricity
  interface_group: efficiency_agriculture_plants
  step_value: 1.0
  unit: "%"
  related_node: agriculture_chp_engine_network_gas_dispatchable
  position: 410
  slide_key: specs_electricity_gas_plants
- key: efficiency_agriculture_chp_engine_dispatchable_network_gas_heat
  interface_group: efficiency_agriculture_plants
  step_value: 1.0
  unit: "%"
  related_node: agriculture_chp_engine_network_gas_dispatchable
  position: 415
  slide_key: specs_electricity_gas_plants
- key: efficiency_agriculture_chp_engine_must_run_network_gas_electricity
  interface_group: efficiency_agriculture_plants
  step_value: 1.0
  unit: "%"
  related_node: agriculture_chp_engine_network_gas_must_run
  position: 420
  slide_key: specs_electricity_gas_plants
- key: efficiency_agriculture_chp_engine_must_run_network_gas_heat
  interface_group: efficiency_agriculture_plants
  step_value: 1.0
  unit: "%"
  related_node: agriculture_chp_engine_network_gas_must_run
  position: 425
  slide_key: specs_electricity_gas_plants
