---
- key: households_insulation_new_residences
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 100
  slide_key: demand_households_insulation
- key: households_insulation_2005_present
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 110
  slide_key: demand_households_insulation
- key: households_insulation_1985_2004
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 120
  slide_key: demand_households_insulation
- key: households_insulation_1965_1984
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 130
  slide_key: demand_households_insulation
- key: households_insulation_1945_1964
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 140
  slide_key: demand_households_insulation
- key: households_insulation_before_1945
  step_value: 0.1
  unit: "%"
  interface_group: households_insulation_levels
  position: 150
  slide_key: demand_households_insulation
