---
- key: transport_useful_demand_passenger_kms
  step_value: 0.1
  unit: "%"
  interface_group: passenger_transport
  position: 100
  slide_key: demand_transport_passenger_transport

- key: transport_cars_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 200
  slide_key: demand_transport_passenger_transport
- key: transport_passenger_trains_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 205
  slide_key: demand_transport_passenger_transport
- key: transport_trams_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 210
  slide_key: demand_transport_passenger_transport
- key: transport_busses_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 215
  slide_key: demand_transport_passenger_transport
- key: transport_motorcycles_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 220
  slide_key: demand_transport_passenger_transport
- key: transport_bicycles_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 225
  slide_key: demand_transport_passenger_transport
- key: transport_planes_share
  share_group: passenger_transport_share
  step_value: 0.1
  unit: "%"
  interface_group: technology_split
  position: 230
  slide_key: demand_transport_passenger_transport