---
- key: climate_relevant_co2_biomass_gas_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 100
  slide_key: emissions_emission_factors_biomass
- key: climate_relevant_co2_biomass_liquid_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 105
  slide_key: emissions_emission_factors_biomass
- key: climate_relevant_co2_biomass_solid_present
  step_value: 0.1
  unit: "%"
  interface_group: present
  command_type: value
  position: 110
  slide_key: emissions_emission_factors_biomass

- key: climate_relevant_co2_biomass_gas_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  command_type: value
  position: 200
  slide_key: emissions_emission_factors_biomass
- key: climate_relevant_co2_biomass_liquid_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  position: 205
  slide_key: emissions_emission_factors_biomass
- key: climate_relevant_co2_biomass_solid_future
  step_value: 0.1
  unit: "%"
  interface_group: future
  command_type: value
  position: 210
  slide_key: emissions_emission_factors_biomass
