---
- key: external_coupling_industry_chemical_other_steam_hot_water_share
  step_value: 0.1
  unit: '%'
  position: 150
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_wood_pellets_share
  step_value: 0.1
  unit: '%'
  position: 155
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_heater_electricity_share
  step_value: 0.1
  unit: '%'
  position: 160
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_network_gas_share
  step_value: 0.1
  unit: '%'
  position: 165
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_coal_share
  step_value: 0.1
  unit: '%'
  position: 170
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_steam_recompression_electricity_share
  step_value: 0.1
  unit: '%'
  position: 175
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_crude_oil_share
  step_value: 0.1
  unit: '%'
  position: 180
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_naphtha_share
  step_value: 0.1
  unit: '%'
  position: 185
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_bionaphtha_share
  step_value: 0.1
  unit: '%'
  position: 190
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_heatpump_water_water_electricity_share
  step_value: 0.1
  unit: '%'
  position: 195
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_burner_hydrogen_share
  step_value: 0.1
  unit: '%'
  position: 255
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_heat
  interface_group: external_coupling_industry_chemical_other_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_residual_heat_share
  step_value: 0.1
  unit: '%'
  position: 340
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_industry_chemical_other_useable_heat
  step_value: 0.001
  unit: '%'
  position: 345
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_industry_chemical_other_electricity
  step_value: 0.001
  unit: '%'
  position: 350
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_total_demand
  step_value: 0.1
  unit: PJ
  position: 355
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_industry_chemical_other_total_non_energetic
  step_value: 0.001
  unit: '%'
  position: 360
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_industry_chemical_other_p2h_capacity
  step_value: 1.0
  unit: MW
  position: 365
  slide_key: demand_industry_chemical_other
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_general
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_wood_pellets_share
  step_value: 0.1
  unit: '%'
  position: 375
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_coal_share
  step_value: 0.1
  unit: '%'
  position: 380
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_crude_oil_share
  step_value: 0.1
  unit: '%'
  position: 385
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_naphtha_share
  step_value: 0.1
  unit: '%'
  position: 390
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_network_gas_share
  step_value: 0.1
  unit: '%'
  position: 395
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_bionaphtha_share
  step_value: 0.1
  unit: '%'
  position: 455
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_industry_chemical_other_non_energetic_hydrogen_share
  step_value: 0.1
  unit: '%'
  position: 465
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_non_energetic
  interface_group: external_coupling_industry_chemical_other_non_energetic
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_natural_gas_input_share
  step_value: 0.1
  unit: '%'
  position: 595
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_ammonia_input_share
  step_value: 0.1
  unit: '%'
  position: 605
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_greengas_input_share
  step_value: 0.1
  unit: '%'
  position: 610
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_wood_pellets_input_share
  step_value: 0.1
  unit: '%'
  position: 615
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_not_defined_input_share
  step_value: 0.1
  unit: '%'
  position: 620
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_methanol_input_share
  step_value: 0.1
  unit: '%'
  position: 625
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_crude_oil_input_share
  step_value: 0.1
  unit: '%'
  position: 630
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_steam_hot_water_input_share
  step_value: 0.1
  unit: '%'
  position: 635
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_waste_mix_input_share
  step_value: 0.1
  unit: '%'
  position: 640
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_electricity_input_share
  step_value: 0.1
  unit: '%'
  position: 645
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_hydrogen_input_share
  step_value: 0.1
  unit: '%'
  position: 650
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_bio_oil_input_share
  step_value: 0.1
  unit: '%'
  position: 655
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_input
  interface_group: external_coupling_industry_chemical_other_transformation_input
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_natural_gas_output_share
  step_value: 0.1
  unit: '%'
  position: 660
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_ammonia_output_share
  step_value: 0.1
  unit: '%'
  position: 665
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_greengas_output_share
  step_value: 0.1
  unit: '%'
  position: 670
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_kerosene_output_share
  step_value: 0.1
  unit: '%'
  position: 675
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_methanol_output_share
  step_value: 0.1
  unit: '%'
  position: 680
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_naphtha_output_share
  step_value: 0.1
  unit: '%'
  position: 685
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_gasoline_output_share
  step_value: 0.1
  unit: '%'
  position: 690
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_diesel_output_share
  step_value: 0.1
  unit: '%'
  position: 695
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_lpg_output_share
  step_value: 0.1
  unit: '%'
  position: 700
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_not_defined_output_share
  step_value: 0.1
  unit: '%'
  position: 705
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_loss_output_share
  step_value: 0.1
  unit: '%'
  position: 710
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_hydrogen_output_share
  step_value: 0.1
  unit: '%'
  position: 715
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_heavy_fuel_oil_output_share
  step_value: 0.1
  unit: '%'
  position: 720
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_bio_kerosene_output_share
  step_value: 0.1
  unit: '%'
  position: 725
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_bionaphtha_output_share
  step_value: 0.1
  unit: '%'
  position: 730
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_biodiesel_output_share
  step_value: 0.1
  unit: '%'
  position: 735
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_energy_chemical_other_transformation_external_coupling_node_refinery_gas_output_share
  step_value: 0.1
  unit: '%'
  position: 740
  slide_key: demand_industry_chemical_other
  share_group: external_coupling_chemical_other_transformation_output
  interface_group: external_coupling_industry_chemical_other_transformation_output
  coupling_icon: true
- key: external_coupling_industry_chemical_other_ccus_capture_potential
  step_value: 1.0
  unit: '%'
  position: 725
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_ccus
  coupling_icon: true
- key: external_coupling_industry_chemical_other_ccus_electricity_use
  step_value: 1.0
  unit: PJ/Mton
  position: 730
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_ccus
  coupling_icon: true
- key: external_coupling_industry_chemical_other_ccus_captured_co2
  step_value: 1.0
  unit: '%'
  position: 735
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_chemical_other_ccus
  coupling_icon: true
