---
- key: transport_vehicle_using_electricity_efficiency
  step_value: 0.1
  unit: "%"
  command_type: efficiency_improvement
  position: 1
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
- key: transport_vehicle_combustion_engine_efficiency
  step_value: 0.1
  unit: "%"
  command_type: efficiency_improvement
  position: 4
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
- key: transport_ships_efficiency
  step_value: 0.1
  unit: "%"
  position: 6
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
- key: transport_planes_efficiency
  step_value: 0.1
  unit: "%"
  position: 7
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
- key: transport_trains_efficiency
  step_value: 0.1
  unit: "%"
  position: 5
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
- key: transport_vehicle_using_hydrogen_efficiency
  step_value: 0.1
  unit: "%"
  position: 2
  interface_group: efficiency_per_year
  slide_key: specs_transport_efficiency_improvement
